name: AT-MODEL
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiobotocore=2.19.0
  - aioitertools=0.7.1
  - appnope=0.1.4
  - asttokens=3.0.0
  - babel=2.16.0
  - blas=1.0
  - boto3=1.36.3
  - botocore=1.36.3
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - commonmark=0.9.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - deprecated=1.2.13
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - freetype=2.13.3
  - fsspec=2024.12.0
  - future=1.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - great_tables=0.14.0
  - htmltools=0.6.0
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - narwhals=1.31.0
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - opentelemetry-api=1.30.0
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - plotly=6.0.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.30.2
  - rpds-py=0.22.3
  - s3fs=2024.12.0
  - s3transfer=0.11.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.5.0
      - dill==0.3.8
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - kaleido==0.2.1
      - matplotlib==3.10.1
      - mergedeep==1.3.4
      - multidict==6.4.3
      - multiprocess==0.70.16
      - numpy==2.2.5
      - packaging==25.0
      - pillow==11.2.1
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pygad==3.4.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.51.3
      - typing-extensions==4.13.2
      - urllib3==2.4.0
      - xxhash==3.5.0
      - yarl==1.20.0
